version: 1.0.{build}

image: Visual Studio 2022
dotnet: 8.0.0

clone_folder: c:\projects\ncalc

before_build:
- Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
& $env:temp\dotnet-install.ps1 -Architecture x64 -Version '8.0.0' -InstallDir "$env:ProgramFiles\dotnet"
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: NCalc.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor c:\projects\ncalc\test\NCalc.Tests\bin\Debug\net461\NCalc.Tests.dll" -output:".\NCalcUnitTestCoverage.xml"
- codecov -f "NCalcUnitTestCoverage.xml"
