version: 1.0.{build}

image: Visual Studio 2022

clone_folder: c:\projects\ncalc

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: NCalc.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor c:\projects\ncalc\test\NCalc.Tests\bin\Debug\net461\NCalc.Tests.dll" -output:".\NCalcUnitTestCoverage.xml"
- codecov -f "NCalcUnitTestCoverage.xml"
