//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.0.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.0.2 NCalc.g 2021-12-17 16:41:36

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace  NCalc 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.0.2")]
[System.CLSCompliant(false)]
public partial class NCalcLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int A=4;
	public const int AND=5;
	public const int B=6;
	public const int C=7;
	public const int D=8;
	public const int DATETIME=9;
	public const int DIGIT=10;
	public const int E=11;
	public const int EXPONENT=12;
	public const int EscapeSequence=13;
	public const int F=14;
	public const int FALSE=15;
	public const int FLOAT=16;
	public const int G=17;
	public const int H=18;
	public const int HexDigit=19;
	public const int I=20;
	public const int ID=21;
	public const int INTEGER=22;
	public const int J=23;
	public const int K=24;
	public const int L=25;
	public const int LETTER=26;
	public const int M=27;
	public const int N=28;
	public const int NAME=29;
	public const int NOT=30;
	public const int O=31;
	public const int OR=32;
	public const int P=33;
	public const int Q=34;
	public const int R=35;
	public const int S=36;
	public const int STRING=37;
	public const int T=38;
	public const int TRUE=39;
	public const int U=40;
	public const int UnicodeEscape=41;
	public const int V=42;
	public const int W=43;
	public const int WS=44;
	public const int X=45;
	public const int Y=46;
	public const int Z=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int T__56=56;
	public const int T__57=57;
	public const int T__58=58;
	public const int T__59=59;
	public const int T__60=60;
	public const int T__61=61;
	public const int T__62=62;
	public const int T__63=63;
	public const int T__64=64;
	public const int T__65=65;
	public const int T__66=66;
	public const int T__67=67;
	public const int T__68=68;
	public const int T__69=69;
	public const int T__70=70;
	public const int T__71=71;
	public const int T__72=72;
	public const int T__73=73;
	public const int T__74=74;
	public const int T__75=75;

	// delegates
	// delegators

	public NCalcLexer()
	{
		OnCreated();
	}

	public NCalcLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public NCalcLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "NCalc.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__48();
	partial void LeaveRule_T__48();

	// $ANTLR start "T__48"
	[GrammarRule("T__48")]
	private void mT__48()
	{
		EnterRule_T__48();
		EnterRule("T__48", 1);
		TraceIn("T__48", 1);
		try
		{
			int _type = T__48;
			int _channel = DefaultTokenChannel;
			// NCalc.g:9:7: ( '!' )
			DebugEnterAlt(1);
			// NCalc.g:9:9: '!'
			{
			DebugLocation(9, 9);
			Match('!'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__48", 1);
			LeaveRule("T__48", 1);
			LeaveRule_T__48();
		}
	}
	// $ANTLR end "T__48"

	partial void EnterRule_T__49();
	partial void LeaveRule_T__49();

	// $ANTLR start "T__49"
	[GrammarRule("T__49")]
	private void mT__49()
	{
		EnterRule_T__49();
		EnterRule("T__49", 2);
		TraceIn("T__49", 2);
		try
		{
			int _type = T__49;
			int _channel = DefaultTokenChannel;
			// NCalc.g:10:7: ( '!=' )
			DebugEnterAlt(1);
			// NCalc.g:10:9: '!='
			{
			DebugLocation(10, 9);
			Match("!="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__49", 2);
			LeaveRule("T__49", 2);
			LeaveRule_T__49();
		}
	}
	// $ANTLR end "T__49"

	partial void EnterRule_T__50();
	partial void LeaveRule_T__50();

	// $ANTLR start "T__50"
	[GrammarRule("T__50")]
	private void mT__50()
	{
		EnterRule_T__50();
		EnterRule("T__50", 3);
		TraceIn("T__50", 3);
		try
		{
			int _type = T__50;
			int _channel = DefaultTokenChannel;
			// NCalc.g:11:7: ( '%' )
			DebugEnterAlt(1);
			// NCalc.g:11:9: '%'
			{
			DebugLocation(11, 9);
			Match('%'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__50", 3);
			LeaveRule("T__50", 3);
			LeaveRule_T__50();
		}
	}
	// $ANTLR end "T__50"

	partial void EnterRule_T__51();
	partial void LeaveRule_T__51();

	// $ANTLR start "T__51"
	[GrammarRule("T__51")]
	private void mT__51()
	{
		EnterRule_T__51();
		EnterRule("T__51", 4);
		TraceIn("T__51", 4);
		try
		{
			int _type = T__51;
			int _channel = DefaultTokenChannel;
			// NCalc.g:12:7: ( '&&' )
			DebugEnterAlt(1);
			// NCalc.g:12:9: '&&'
			{
			DebugLocation(12, 9);
			Match("&&"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__51", 4);
			LeaveRule("T__51", 4);
			LeaveRule_T__51();
		}
	}
	// $ANTLR end "T__51"

	partial void EnterRule_T__52();
	partial void LeaveRule_T__52();

	// $ANTLR start "T__52"
	[GrammarRule("T__52")]
	private void mT__52()
	{
		EnterRule_T__52();
		EnterRule("T__52", 5);
		TraceIn("T__52", 5);
		try
		{
			int _type = T__52;
			int _channel = DefaultTokenChannel;
			// NCalc.g:13:7: ( '&' )
			DebugEnterAlt(1);
			// NCalc.g:13:9: '&'
			{
			DebugLocation(13, 9);
			Match('&'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__52", 5);
			LeaveRule("T__52", 5);
			LeaveRule_T__52();
		}
	}
	// $ANTLR end "T__52"

	partial void EnterRule_T__53();
	partial void LeaveRule_T__53();

	// $ANTLR start "T__53"
	[GrammarRule("T__53")]
	private void mT__53()
	{
		EnterRule_T__53();
		EnterRule("T__53", 6);
		TraceIn("T__53", 6);
		try
		{
			int _type = T__53;
			int _channel = DefaultTokenChannel;
			// NCalc.g:14:7: ( '(' )
			DebugEnterAlt(1);
			// NCalc.g:14:9: '('
			{
			DebugLocation(14, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__53", 6);
			LeaveRule("T__53", 6);
			LeaveRule_T__53();
		}
	}
	// $ANTLR end "T__53"

	partial void EnterRule_T__54();
	partial void LeaveRule_T__54();

	// $ANTLR start "T__54"
	[GrammarRule("T__54")]
	private void mT__54()
	{
		EnterRule_T__54();
		EnterRule("T__54", 7);
		TraceIn("T__54", 7);
		try
		{
			int _type = T__54;
			int _channel = DefaultTokenChannel;
			// NCalc.g:15:7: ( ')' )
			DebugEnterAlt(1);
			// NCalc.g:15:9: ')'
			{
			DebugLocation(15, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__54", 7);
			LeaveRule("T__54", 7);
			LeaveRule_T__54();
		}
	}
	// $ANTLR end "T__54"

	partial void EnterRule_T__55();
	partial void LeaveRule_T__55();

	// $ANTLR start "T__55"
	[GrammarRule("T__55")]
	private void mT__55()
	{
		EnterRule_T__55();
		EnterRule("T__55", 8);
		TraceIn("T__55", 8);
		try
		{
			int _type = T__55;
			int _channel = DefaultTokenChannel;
			// NCalc.g:16:7: ( '*' )
			DebugEnterAlt(1);
			// NCalc.g:16:9: '*'
			{
			DebugLocation(16, 9);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__55", 8);
			LeaveRule("T__55", 8);
			LeaveRule_T__55();
		}
	}
	// $ANTLR end "T__55"

	partial void EnterRule_T__56();
	partial void LeaveRule_T__56();

	// $ANTLR start "T__56"
	[GrammarRule("T__56")]
	private void mT__56()
	{
		EnterRule_T__56();
		EnterRule("T__56", 9);
		TraceIn("T__56", 9);
		try
		{
			int _type = T__56;
			int _channel = DefaultTokenChannel;
			// NCalc.g:17:7: ( '**' )
			DebugEnterAlt(1);
			// NCalc.g:17:9: '**'
			{
			DebugLocation(17, 9);
			Match("**"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__56", 9);
			LeaveRule("T__56", 9);
			LeaveRule_T__56();
		}
	}
	// $ANTLR end "T__56"

	partial void EnterRule_T__57();
	partial void LeaveRule_T__57();

	// $ANTLR start "T__57"
	[GrammarRule("T__57")]
	private void mT__57()
	{
		EnterRule_T__57();
		EnterRule("T__57", 10);
		TraceIn("T__57", 10);
		try
		{
			int _type = T__57;
			int _channel = DefaultTokenChannel;
			// NCalc.g:18:7: ( '+' )
			DebugEnterAlt(1);
			// NCalc.g:18:9: '+'
			{
			DebugLocation(18, 9);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__57", 10);
			LeaveRule("T__57", 10);
			LeaveRule_T__57();
		}
	}
	// $ANTLR end "T__57"

	partial void EnterRule_T__58();
	partial void LeaveRule_T__58();

	// $ANTLR start "T__58"
	[GrammarRule("T__58")]
	private void mT__58()
	{
		EnterRule_T__58();
		EnterRule("T__58", 11);
		TraceIn("T__58", 11);
		try
		{
			int _type = T__58;
			int _channel = DefaultTokenChannel;
			// NCalc.g:19:7: ( ',' )
			DebugEnterAlt(1);
			// NCalc.g:19:9: ','
			{
			DebugLocation(19, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__58", 11);
			LeaveRule("T__58", 11);
			LeaveRule_T__58();
		}
	}
	// $ANTLR end "T__58"

	partial void EnterRule_T__59();
	partial void LeaveRule_T__59();

	// $ANTLR start "T__59"
	[GrammarRule("T__59")]
	private void mT__59()
	{
		EnterRule_T__59();
		EnterRule("T__59", 12);
		TraceIn("T__59", 12);
		try
		{
			int _type = T__59;
			int _channel = DefaultTokenChannel;
			// NCalc.g:20:7: ( '-' )
			DebugEnterAlt(1);
			// NCalc.g:20:9: '-'
			{
			DebugLocation(20, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__59", 12);
			LeaveRule("T__59", 12);
			LeaveRule_T__59();
		}
	}
	// $ANTLR end "T__59"

	partial void EnterRule_T__60();
	partial void LeaveRule_T__60();

	// $ANTLR start "T__60"
	[GrammarRule("T__60")]
	private void mT__60()
	{
		EnterRule_T__60();
		EnterRule("T__60", 13);
		TraceIn("T__60", 13);
		try
		{
			int _type = T__60;
			int _channel = DefaultTokenChannel;
			// NCalc.g:21:7: ( '/' )
			DebugEnterAlt(1);
			// NCalc.g:21:9: '/'
			{
			DebugLocation(21, 9);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__60", 13);
			LeaveRule("T__60", 13);
			LeaveRule_T__60();
		}
	}
	// $ANTLR end "T__60"

	partial void EnterRule_T__61();
	partial void LeaveRule_T__61();

	// $ANTLR start "T__61"
	[GrammarRule("T__61")]
	private void mT__61()
	{
		EnterRule_T__61();
		EnterRule("T__61", 14);
		TraceIn("T__61", 14);
		try
		{
			int _type = T__61;
			int _channel = DefaultTokenChannel;
			// NCalc.g:22:7: ( ':' )
			DebugEnterAlt(1);
			// NCalc.g:22:9: ':'
			{
			DebugLocation(22, 9);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__61", 14);
			LeaveRule("T__61", 14);
			LeaveRule_T__61();
		}
	}
	// $ANTLR end "T__61"

	partial void EnterRule_T__62();
	partial void LeaveRule_T__62();

	// $ANTLR start "T__62"
	[GrammarRule("T__62")]
	private void mT__62()
	{
		EnterRule_T__62();
		EnterRule("T__62", 15);
		TraceIn("T__62", 15);
		try
		{
			int _type = T__62;
			int _channel = DefaultTokenChannel;
			// NCalc.g:23:7: ( '<' )
			DebugEnterAlt(1);
			// NCalc.g:23:9: '<'
			{
			DebugLocation(23, 9);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__62", 15);
			LeaveRule("T__62", 15);
			LeaveRule_T__62();
		}
	}
	// $ANTLR end "T__62"

	partial void EnterRule_T__63();
	partial void LeaveRule_T__63();

	// $ANTLR start "T__63"
	[GrammarRule("T__63")]
	private void mT__63()
	{
		EnterRule_T__63();
		EnterRule("T__63", 16);
		TraceIn("T__63", 16);
		try
		{
			int _type = T__63;
			int _channel = DefaultTokenChannel;
			// NCalc.g:24:7: ( '<<' )
			DebugEnterAlt(1);
			// NCalc.g:24:9: '<<'
			{
			DebugLocation(24, 9);
			Match("<<"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__63", 16);
			LeaveRule("T__63", 16);
			LeaveRule_T__63();
		}
	}
	// $ANTLR end "T__63"

	partial void EnterRule_T__64();
	partial void LeaveRule_T__64();

	// $ANTLR start "T__64"
	[GrammarRule("T__64")]
	private void mT__64()
	{
		EnterRule_T__64();
		EnterRule("T__64", 17);
		TraceIn("T__64", 17);
		try
		{
			int _type = T__64;
			int _channel = DefaultTokenChannel;
			// NCalc.g:25:7: ( '<=' )
			DebugEnterAlt(1);
			// NCalc.g:25:9: '<='
			{
			DebugLocation(25, 9);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__64", 17);
			LeaveRule("T__64", 17);
			LeaveRule_T__64();
		}
	}
	// $ANTLR end "T__64"

	partial void EnterRule_T__65();
	partial void LeaveRule_T__65();

	// $ANTLR start "T__65"
	[GrammarRule("T__65")]
	private void mT__65()
	{
		EnterRule_T__65();
		EnterRule("T__65", 18);
		TraceIn("T__65", 18);
		try
		{
			int _type = T__65;
			int _channel = DefaultTokenChannel;
			// NCalc.g:26:7: ( '<>' )
			DebugEnterAlt(1);
			// NCalc.g:26:9: '<>'
			{
			DebugLocation(26, 9);
			Match("<>"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__65", 18);
			LeaveRule("T__65", 18);
			LeaveRule_T__65();
		}
	}
	// $ANTLR end "T__65"

	partial void EnterRule_T__66();
	partial void LeaveRule_T__66();

	// $ANTLR start "T__66"
	[GrammarRule("T__66")]
	private void mT__66()
	{
		EnterRule_T__66();
		EnterRule("T__66", 19);
		TraceIn("T__66", 19);
		try
		{
			int _type = T__66;
			int _channel = DefaultTokenChannel;
			// NCalc.g:27:7: ( '=' )
			DebugEnterAlt(1);
			// NCalc.g:27:9: '='
			{
			DebugLocation(27, 9);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__66", 19);
			LeaveRule("T__66", 19);
			LeaveRule_T__66();
		}
	}
	// $ANTLR end "T__66"

	partial void EnterRule_T__67();
	partial void LeaveRule_T__67();

	// $ANTLR start "T__67"
	[GrammarRule("T__67")]
	private void mT__67()
	{
		EnterRule_T__67();
		EnterRule("T__67", 20);
		TraceIn("T__67", 20);
		try
		{
			int _type = T__67;
			int _channel = DefaultTokenChannel;
			// NCalc.g:28:7: ( '==' )
			DebugEnterAlt(1);
			// NCalc.g:28:9: '=='
			{
			DebugLocation(28, 9);
			Match("=="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__67", 20);
			LeaveRule("T__67", 20);
			LeaveRule_T__67();
		}
	}
	// $ANTLR end "T__67"

	partial void EnterRule_T__68();
	partial void LeaveRule_T__68();

	// $ANTLR start "T__68"
	[GrammarRule("T__68")]
	private void mT__68()
	{
		EnterRule_T__68();
		EnterRule("T__68", 21);
		TraceIn("T__68", 21);
		try
		{
			int _type = T__68;
			int _channel = DefaultTokenChannel;
			// NCalc.g:29:7: ( '>' )
			DebugEnterAlt(1);
			// NCalc.g:29:9: '>'
			{
			DebugLocation(29, 9);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__68", 21);
			LeaveRule("T__68", 21);
			LeaveRule_T__68();
		}
	}
	// $ANTLR end "T__68"

	partial void EnterRule_T__69();
	partial void LeaveRule_T__69();

	// $ANTLR start "T__69"
	[GrammarRule("T__69")]
	private void mT__69()
	{
		EnterRule_T__69();
		EnterRule("T__69", 22);
		TraceIn("T__69", 22);
		try
		{
			int _type = T__69;
			int _channel = DefaultTokenChannel;
			// NCalc.g:30:7: ( '>=' )
			DebugEnterAlt(1);
			// NCalc.g:30:9: '>='
			{
			DebugLocation(30, 9);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__69", 22);
			LeaveRule("T__69", 22);
			LeaveRule_T__69();
		}
	}
	// $ANTLR end "T__69"

	partial void EnterRule_T__70();
	partial void LeaveRule_T__70();

	// $ANTLR start "T__70"
	[GrammarRule("T__70")]
	private void mT__70()
	{
		EnterRule_T__70();
		EnterRule("T__70", 23);
		TraceIn("T__70", 23);
		try
		{
			int _type = T__70;
			int _channel = DefaultTokenChannel;
			// NCalc.g:31:7: ( '>>' )
			DebugEnterAlt(1);
			// NCalc.g:31:9: '>>'
			{
			DebugLocation(31, 9);
			Match(">>"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__70", 23);
			LeaveRule("T__70", 23);
			LeaveRule_T__70();
		}
	}
	// $ANTLR end "T__70"

	partial void EnterRule_T__71();
	partial void LeaveRule_T__71();

	// $ANTLR start "T__71"
	[GrammarRule("T__71")]
	private void mT__71()
	{
		EnterRule_T__71();
		EnterRule("T__71", 24);
		TraceIn("T__71", 24);
		try
		{
			int _type = T__71;
			int _channel = DefaultTokenChannel;
			// NCalc.g:32:7: ( '?' )
			DebugEnterAlt(1);
			// NCalc.g:32:9: '?'
			{
			DebugLocation(32, 9);
			Match('?'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__71", 24);
			LeaveRule("T__71", 24);
			LeaveRule_T__71();
		}
	}
	// $ANTLR end "T__71"

	partial void EnterRule_T__72();
	partial void LeaveRule_T__72();

	// $ANTLR start "T__72"
	[GrammarRule("T__72")]
	private void mT__72()
	{
		EnterRule_T__72();
		EnterRule("T__72", 25);
		TraceIn("T__72", 25);
		try
		{
			int _type = T__72;
			int _channel = DefaultTokenChannel;
			// NCalc.g:33:7: ( '^' )
			DebugEnterAlt(1);
			// NCalc.g:33:9: '^'
			{
			DebugLocation(33, 9);
			Match('^'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__72", 25);
			LeaveRule("T__72", 25);
			LeaveRule_T__72();
		}
	}
	// $ANTLR end "T__72"

	partial void EnterRule_T__73();
	partial void LeaveRule_T__73();

	// $ANTLR start "T__73"
	[GrammarRule("T__73")]
	private void mT__73()
	{
		EnterRule_T__73();
		EnterRule("T__73", 26);
		TraceIn("T__73", 26);
		try
		{
			int _type = T__73;
			int _channel = DefaultTokenChannel;
			// NCalc.g:34:7: ( '|' )
			DebugEnterAlt(1);
			// NCalc.g:34:9: '|'
			{
			DebugLocation(34, 9);
			Match('|'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__73", 26);
			LeaveRule("T__73", 26);
			LeaveRule_T__73();
		}
	}
	// $ANTLR end "T__73"

	partial void EnterRule_T__74();
	partial void LeaveRule_T__74();

	// $ANTLR start "T__74"
	[GrammarRule("T__74")]
	private void mT__74()
	{
		EnterRule_T__74();
		EnterRule("T__74", 27);
		TraceIn("T__74", 27);
		try
		{
			int _type = T__74;
			int _channel = DefaultTokenChannel;
			// NCalc.g:35:7: ( '||' )
			DebugEnterAlt(1);
			// NCalc.g:35:9: '||'
			{
			DebugLocation(35, 9);
			Match("||"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__74", 27);
			LeaveRule("T__74", 27);
			LeaveRule_T__74();
		}
	}
	// $ANTLR end "T__74"

	partial void EnterRule_T__75();
	partial void LeaveRule_T__75();

	// $ANTLR start "T__75"
	[GrammarRule("T__75")]
	private void mT__75()
	{
		EnterRule_T__75();
		EnterRule("T__75", 28);
		TraceIn("T__75", 28);
		try
		{
			int _type = T__75;
			int _channel = DefaultTokenChannel;
			// NCalc.g:36:7: ( '~' )
			DebugEnterAlt(1);
			// NCalc.g:36:9: '~'
			{
			DebugLocation(36, 9);
			Match('~'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__75", 28);
			LeaveRule("T__75", 28);
			LeaveRule_T__75();
		}
	}
	// $ANTLR end "T__75"

	partial void EnterRule_TRUE();
	partial void LeaveRule_TRUE();

	// $ANTLR start "TRUE"
	[GrammarRule("TRUE")]
	private void mTRUE()
	{
		EnterRule_TRUE();
		EnterRule("TRUE", 29);
		TraceIn("TRUE", 29);
		try
		{
			int _type = TRUE;
			int _channel = DefaultTokenChannel;
			// NCalc.g:248:5: ( T R U E )
			DebugEnterAlt(1);
			// NCalc.g:248:7: T R U E
			{
			DebugLocation(248, 7);
			mT(); 
			DebugLocation(248, 9);
			mR(); 
			DebugLocation(248, 11);
			mU(); 
			DebugLocation(248, 13);
			mE(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TRUE", 29);
			LeaveRule("TRUE", 29);
			LeaveRule_TRUE();
		}
	}
	// $ANTLR end "TRUE"

	partial void EnterRule_FALSE();
	partial void LeaveRule_FALSE();

	// $ANTLR start "FALSE"
	[GrammarRule("FALSE")]
	private void mFALSE()
	{
		EnterRule_FALSE();
		EnterRule("FALSE", 30);
		TraceIn("FALSE", 30);
		try
		{
			int _type = FALSE;
			int _channel = DefaultTokenChannel;
			// NCalc.g:249:6: ( F A L S E )
			DebugEnterAlt(1);
			// NCalc.g:249:8: F A L S E
			{
			DebugLocation(249, 8);
			mF(); 
			DebugLocation(249, 10);
			mA(); 
			DebugLocation(249, 12);
			mL(); 
			DebugLocation(249, 14);
			mS(); 
			DebugLocation(249, 16);
			mE(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FALSE", 30);
			LeaveRule("FALSE", 30);
			LeaveRule_FALSE();
		}
	}
	// $ANTLR end "FALSE"

	partial void EnterRule_AND();
	partial void LeaveRule_AND();

	// $ANTLR start "AND"
	[GrammarRule("AND")]
	private void mAND()
	{
		EnterRule_AND();
		EnterRule("AND", 31);
		TraceIn("AND", 31);
		try
		{
			int _type = AND;
			int _channel = DefaultTokenChannel;
			// NCalc.g:250:4: ( A N D )
			DebugEnterAlt(1);
			// NCalc.g:250:6: A N D
			{
			DebugLocation(250, 6);
			mA(); 
			DebugLocation(250, 8);
			mN(); 
			DebugLocation(250, 10);
			mD(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("AND", 31);
			LeaveRule("AND", 31);
			LeaveRule_AND();
		}
	}
	// $ANTLR end "AND"

	partial void EnterRule_OR();
	partial void LeaveRule_OR();

	// $ANTLR start "OR"
	[GrammarRule("OR")]
	private void mOR()
	{
		EnterRule_OR();
		EnterRule("OR", 32);
		TraceIn("OR", 32);
		try
		{
			int _type = OR;
			int _channel = DefaultTokenChannel;
			// NCalc.g:251:3: ( O R )
			DebugEnterAlt(1);
			// NCalc.g:251:6: O R
			{
			DebugLocation(251, 6);
			mO(); 
			DebugLocation(251, 8);
			mR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OR", 32);
			LeaveRule("OR", 32);
			LeaveRule_OR();
		}
	}
	// $ANTLR end "OR"

	partial void EnterRule_NOT();
	partial void LeaveRule_NOT();

	// $ANTLR start "NOT"
	[GrammarRule("NOT")]
	private void mNOT()
	{
		EnterRule_NOT();
		EnterRule("NOT", 33);
		TraceIn("NOT", 33);
		try
		{
			int _type = NOT;
			int _channel = DefaultTokenChannel;
			// NCalc.g:252:4: ( N O T )
			DebugEnterAlt(1);
			// NCalc.g:252:6: N O T
			{
			DebugLocation(252, 6);
			mN(); 
			DebugLocation(252, 8);
			mO(); 
			DebugLocation(252, 10);
			mT(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NOT", 33);
			LeaveRule("NOT", 33);
			LeaveRule_NOT();
		}
	}
	// $ANTLR end "NOT"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 34);
		TraceIn("ID", 34);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// NCalc.g:255:2: ( LETTER ( LETTER | DIGIT )* )
			DebugEnterAlt(1);
			// NCalc.g:255:5: LETTER ( LETTER | DIGIT )*
			{
			DebugLocation(255, 5);
			mLETTER(); 
			DebugLocation(255, 12);
			// NCalc.g:255:12: ( LETTER | DIGIT )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if (((LA1_1>='0' && LA1_1<='9')||(LA1_1>='A' && LA1_1<='Z')||LA1_1=='_'||(LA1_1>='a' && LA1_1<='z')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:
					{
					DebugLocation(255, 12);
					input.Consume();


					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 34);
			LeaveRule("ID", 34);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_INTEGER();
	partial void LeaveRule_INTEGER();

	// $ANTLR start "INTEGER"
	[GrammarRule("INTEGER")]
	private void mINTEGER()
	{
		EnterRule_INTEGER();
		EnterRule("INTEGER", 35);
		TraceIn("INTEGER", 35);
		try
		{
			int _type = INTEGER;
			int _channel = DefaultTokenChannel;
			// NCalc.g:259:2: ( ( DIGIT )+ )
			DebugEnterAlt(1);
			// NCalc.g:259:4: ( DIGIT )+
			{
			DebugLocation(259, 4);
			// NCalc.g:259:4: ( DIGIT )+
			int cnt2=0;
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if (((LA2_1>='0' && LA2_1<='9')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:
					{
					DebugLocation(259, 4);
					input.Consume();


					}
					break;

				default:
					if (cnt2 >= 1)
						goto loop2;

					EarlyExitException eee2 = new EarlyExitException( 2, input );
					DebugRecognitionException(eee2);
					throw eee2;
				}
				cnt2++;
			}
			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INTEGER", 35);
			LeaveRule("INTEGER", 35);
			LeaveRule_INTEGER();
		}
	}
	// $ANTLR end "INTEGER"

	partial void EnterRule_FLOAT();
	partial void LeaveRule_FLOAT();

	// $ANTLR start "FLOAT"
	[GrammarRule("FLOAT")]
	private void mFLOAT()
	{
		EnterRule_FLOAT();
		EnterRule("FLOAT", 36);
		TraceIn("FLOAT", 36);
		try
		{
			int _type = FLOAT;
			int _channel = DefaultTokenChannel;
			// NCalc.g:263:2: ( ( DIGIT )* '.' ( DIGIT )+ ( EXPONENT )? | ( DIGIT )+ '.' ( DIGIT )* ( EXPONENT )? | ( DIGIT )+ EXPONENT )
			int alt10=3;
			try { DebugEnterDecision(10, false);
			try
			{
				alt10 = dfa10.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// NCalc.g:263:4: ( DIGIT )* '.' ( DIGIT )+ ( EXPONENT )?
				{
				DebugLocation(263, 4);
				// NCalc.g:263:4: ( DIGIT )*
				try { DebugEnterSubRule(3);
				while (true)
				{
					int alt3=2;
					try { DebugEnterDecision(3, false);
					int LA3_1 = input.LA(1);

					if (((LA3_1>='0' && LA3_1<='9')))
					{
						alt3 = 1;
					}


					} finally { DebugExitDecision(3); }
					switch ( alt3 )
					{
					case 1:
						DebugEnterAlt(1);
						// NCalc.g:
						{
						DebugLocation(263, 4);
						input.Consume();


						}
						break;

					default:
						goto loop3;
					}
				}

				loop3:
					;

				} finally { DebugExitSubRule(3); }

				DebugLocation(263, 11);
				Match('.'); 
				DebugLocation(263, 15);
				// NCalc.g:263:15: ( DIGIT )+
				int cnt4=0;
				try { DebugEnterSubRule(4);
				while (true)
				{
					int alt4=2;
					try { DebugEnterDecision(4, false);
					int LA4_1 = input.LA(1);

					if (((LA4_1>='0' && LA4_1<='9')))
					{
						alt4 = 1;
					}


					} finally { DebugExitDecision(4); }
					switch (alt4)
					{
					case 1:
						DebugEnterAlt(1);
						// NCalc.g:
						{
						DebugLocation(263, 15);
						input.Consume();


						}
						break;

					default:
						if (cnt4 >= 1)
							goto loop4;

						EarlyExitException eee4 = new EarlyExitException( 4, input );
						DebugRecognitionException(eee4);
						throw eee4;
					}
					cnt4++;
				}
				loop4:
					;

				} finally { DebugExitSubRule(4); }

				DebugLocation(263, 22);
				// NCalc.g:263:22: ( EXPONENT )?
				int alt5=2;
				try { DebugEnterSubRule(5);
				try { DebugEnterDecision(5, false);
				int LA5_1 = input.LA(1);

				if ((LA5_1=='E'||LA5_1=='e'))
				{
					alt5 = 1;
				}
				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:263:22: EXPONENT
					{
					DebugLocation(263, 22);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(5); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// NCalc.g:264:4: ( DIGIT )+ '.' ( DIGIT )* ( EXPONENT )?
				{
				DebugLocation(264, 4);
				// NCalc.g:264:4: ( DIGIT )+
				int cnt6=0;
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_1 = input.LA(1);

					if (((LA6_1>='0' && LA6_1<='9')))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch (alt6)
					{
					case 1:
						DebugEnterAlt(1);
						// NCalc.g:
						{
						DebugLocation(264, 4);
						input.Consume();


						}
						break;

					default:
						if (cnt6 >= 1)
							goto loop6;

						EarlyExitException eee6 = new EarlyExitException( 6, input );
						DebugRecognitionException(eee6);
						throw eee6;
					}
					cnt6++;
				}
				loop6:
					;

				} finally { DebugExitSubRule(6); }

				DebugLocation(264, 11);
				Match('.'); 
				DebugLocation(264, 15);
				// NCalc.g:264:15: ( DIGIT )*
				try { DebugEnterSubRule(7);
				while (true)
				{
					int alt7=2;
					try { DebugEnterDecision(7, false);
					int LA7_1 = input.LA(1);

					if (((LA7_1>='0' && LA7_1<='9')))
					{
						alt7 = 1;
					}


					} finally { DebugExitDecision(7); }
					switch ( alt7 )
					{
					case 1:
						DebugEnterAlt(1);
						// NCalc.g:
						{
						DebugLocation(264, 15);
						input.Consume();


						}
						break;

					default:
						goto loop7;
					}
				}

				loop7:
					;

				} finally { DebugExitSubRule(7); }

				DebugLocation(264, 22);
				// NCalc.g:264:22: ( EXPONENT )?
				int alt8=2;
				try { DebugEnterSubRule(8);
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if ((LA8_1=='E'||LA8_1=='e'))
				{
					alt8 = 1;
				}
				} finally { DebugExitDecision(8); }
				switch (alt8)
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:264:22: EXPONENT
					{
					DebugLocation(264, 22);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(8); }


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// NCalc.g:265:4: ( DIGIT )+ EXPONENT
				{
				DebugLocation(265, 4);
				// NCalc.g:265:4: ( DIGIT )+
				int cnt9=0;
				try { DebugEnterSubRule(9);
				while (true)
				{
					int alt9=2;
					try { DebugEnterDecision(9, false);
					int LA9_1 = input.LA(1);

					if (((LA9_1>='0' && LA9_1<='9')))
					{
						alt9 = 1;
					}


					} finally { DebugExitDecision(9); }
					switch (alt9)
					{
					case 1:
						DebugEnterAlt(1);
						// NCalc.g:
						{
						DebugLocation(265, 4);
						input.Consume();


						}
						break;

					default:
						if (cnt9 >= 1)
							goto loop9;

						EarlyExitException eee9 = new EarlyExitException( 9, input );
						DebugRecognitionException(eee9);
						throw eee9;
					}
					cnt9++;
				}
				loop9:
					;

				} finally { DebugExitSubRule(9); }

				DebugLocation(265, 11);
				mEXPONENT(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FLOAT", 36);
			LeaveRule("FLOAT", 36);
			LeaveRule_FLOAT();
		}
	}
	// $ANTLR end "FLOAT"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 37);
		TraceIn("STRING", 37);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// NCalc.g:269:6: ( '\\'' ( EscapeSequence | ( options {greedy=false; } :~ ( '\\u0000' .. '\\u001f' | '\\\\' | '\\'' ) ) )* '\\'' )
			DebugEnterAlt(1);
			// NCalc.g:269:10: '\\'' ( EscapeSequence | ( options {greedy=false; } :~ ( '\\u0000' .. '\\u001f' | '\\\\' | '\\'' ) ) )* '\\''
			{
			DebugLocation(269, 10);
			Match('\''); 
			DebugLocation(269, 15);
			// NCalc.g:269:15: ( EscapeSequence | ( options {greedy=false; } :~ ( '\\u0000' .. '\\u001f' | '\\\\' | '\\'' ) ) )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=3;
				try { DebugEnterDecision(11, false);
				int LA11_1 = input.LA(1);

				if ((LA11_1=='\\'))
				{
					alt11 = 1;
				}
				else if (((LA11_1>=' ' && LA11_1<='&')||(LA11_1>='(' && LA11_1<='[')||(LA11_1>=']' && LA11_1<='\uFFFF')))
				{
					alt11 = 2;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:269:17: EscapeSequence
					{
					DebugLocation(269, 17);
					mEscapeSequence(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// NCalc.g:269:34: ( options {greedy=false; } :~ ( '\\u0000' .. '\\u001f' | '\\\\' | '\\'' ) )
					{
					DebugLocation(269, 34);
					// NCalc.g:269:34: ( options {greedy=false; } :~ ( '\\u0000' .. '\\u001f' | '\\\\' | '\\'' ) )
					DebugEnterAlt(1);
					// NCalc.g:269:61: ~ ( '\\u0000' .. '\\u001f' | '\\\\' | '\\'' )
					{
					DebugLocation(269, 61);
					input.Consume();


					}


					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }

			DebugLocation(269, 103);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 37);
			LeaveRule("STRING", 37);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_DATETIME();
	partial void LeaveRule_DATETIME();

	// $ANTLR start "DATETIME"
	[GrammarRule("DATETIME")]
	private void mDATETIME()
	{
		EnterRule_DATETIME();
		EnterRule("DATETIME", 38);
		TraceIn("DATETIME", 38);
		try
		{
			int _type = DATETIME;
			int _channel = DefaultTokenChannel;
			// NCalc.g:273:3: ( '#' ( options {greedy=false; } : (~ ( '#' ) )* ) '#' )
			DebugEnterAlt(1);
			// NCalc.g:273:5: '#' ( options {greedy=false; } : (~ ( '#' ) )* ) '#'
			{
			DebugLocation(273, 5);
			Match('#'); 
			DebugLocation(273, 9);
			// NCalc.g:273:9: ( options {greedy=false; } : (~ ( '#' ) )* )
			DebugEnterAlt(1);
			// NCalc.g:273:36: (~ ( '#' ) )*
			{
			DebugLocation(273, 36);
			// NCalc.g:273:36: (~ ( '#' ) )*
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_1 = input.LA(1);

				if (((LA12_1>='\u0000' && LA12_1<='\"')||(LA12_1>='$' && LA12_1<='\uFFFF')))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch ( alt12 )
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:
					{
					DebugLocation(273, 36);
					input.Consume();


					}
					break;

				default:
					goto loop12;
				}
			}

			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

			DebugLocation(273, 45);
			Match('#'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DATETIME", 38);
			LeaveRule("DATETIME", 38);
			LeaveRule_DATETIME();
		}
	}
	// $ANTLR end "DATETIME"

	partial void EnterRule_NAME();
	partial void LeaveRule_NAME();

	// $ANTLR start "NAME"
	[GrammarRule("NAME")]
	private void mNAME()
	{
		EnterRule_NAME();
		EnterRule("NAME", 39);
		TraceIn("NAME", 39);
		try
		{
			int _type = NAME;
			int _channel = DefaultTokenChannel;
			// NCalc.g:276:6: ( '[' ( options {greedy=false; } : (~ ( ']' ) )* ) ']' )
			DebugEnterAlt(1);
			// NCalc.g:276:8: '[' ( options {greedy=false; } : (~ ( ']' ) )* ) ']'
			{
			DebugLocation(276, 8);
			Match('['); 
			DebugLocation(276, 12);
			// NCalc.g:276:12: ( options {greedy=false; } : (~ ( ']' ) )* )
			DebugEnterAlt(1);
			// NCalc.g:276:39: (~ ( ']' ) )*
			{
			DebugLocation(276, 39);
			// NCalc.g:276:39: (~ ( ']' ) )*
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				int LA13_1 = input.LA(1);

				if (((LA13_1>='\u0000' && LA13_1<='\\')||(LA13_1>='^' && LA13_1<='\uFFFF')))
				{
					alt13 = 1;
				}


				} finally { DebugExitDecision(13); }
				switch ( alt13 )
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:
					{
					DebugLocation(276, 39);
					input.Consume();


					}
					break;

				default:
					goto loop13;
				}
			}

			loop13:
				;

			} finally { DebugExitSubRule(13); }


			}

			DebugLocation(276, 48);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NAME", 39);
			LeaveRule("NAME", 39);
			LeaveRule_NAME();
		}
	}
	// $ANTLR end "NAME"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 40);
		TraceIn("EXPONENT", 40);
		try
		{
			int _type = EXPONENT;
			int _channel = DefaultTokenChannel;
			// NCalc.g:280:2: ( ( 'E' | 'e' ) ( '+' | '-' )? ( DIGIT )+ )
			DebugEnterAlt(1);
			// NCalc.g:280:4: ( 'E' | 'e' ) ( '+' | '-' )? ( DIGIT )+
			{
			DebugLocation(280, 4);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(280, 14);
			// NCalc.g:280:14: ( '+' | '-' )?
			int alt14=2;
			try { DebugEnterSubRule(14);
			try { DebugEnterDecision(14, false);
			int LA14_1 = input.LA(1);

			if ((LA14_1=='+'||LA14_1=='-'))
			{
				alt14 = 1;
			}
			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// NCalc.g:
				{
				DebugLocation(280, 14);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(14); }

			DebugLocation(280, 25);
			// NCalc.g:280:25: ( DIGIT )+
			int cnt15=0;
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=2;
				try { DebugEnterDecision(15, false);
				int LA15_1 = input.LA(1);

				if (((LA15_1>='0' && LA15_1<='9')))
				{
					alt15 = 1;
				}


				} finally { DebugExitDecision(15); }
				switch (alt15)
				{
				case 1:
					DebugEnterAlt(1);
					// NCalc.g:
					{
					DebugLocation(280, 25);
					input.Consume();


					}
					break;

				default:
					if (cnt15 >= 1)
						goto loop15;

					EarlyExitException eee15 = new EarlyExitException( 15, input );
					DebugRecognitionException(eee15);
					throw eee15;
				}
				cnt15++;
			}
			loop15:
				;

			} finally { DebugExitSubRule(15); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EXPONENT", 40);
			LeaveRule("EXPONENT", 40);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_LETTER();
	partial void LeaveRule_LETTER();

	// $ANTLR start "LETTER"
	[GrammarRule("LETTER")]
	private void mLETTER()
	{
		EnterRule_LETTER();
		EnterRule("LETTER", 41);
		TraceIn("LETTER", 41);
		try
		{
			// NCalc.g:284:2: ( 'a' .. 'z' | 'A' .. 'Z' | '_' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(284, 2);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("LETTER", 41);
			LeaveRule("LETTER", 41);
			LeaveRule_LETTER();
		}
	}
	// $ANTLR end "LETTER"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 42);
		TraceIn("DIGIT", 42);
		try
		{
			// NCalc.g:290:2: ( '0' .. '9' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(290, 2);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 42);
			LeaveRule("DIGIT", 42);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_EscapeSequence();
	partial void LeaveRule_EscapeSequence();

	// $ANTLR start "EscapeSequence"
	[GrammarRule("EscapeSequence")]
	private void mEscapeSequence()
	{
		EnterRule_EscapeSequence();
		EnterRule("EscapeSequence", 43);
		TraceIn("EscapeSequence", 43);
		try
		{
			// NCalc.g:294:2: ( '\\\\' ( 'n' | 'r' | 't' | '\\'' | '\\\\' | UnicodeEscape ) )
			DebugEnterAlt(1);
			// NCalc.g:294:4: '\\\\' ( 'n' | 'r' | 't' | '\\'' | '\\\\' | UnicodeEscape )
			{
			DebugLocation(294, 4);
			Match('\\'); 
			DebugLocation(295, 4);
			// NCalc.g:295:4: ( 'n' | 'r' | 't' | '\\'' | '\\\\' | UnicodeEscape )
			int alt16=6;
			try { DebugEnterSubRule(16);
			try { DebugEnterDecision(16, false);
			switch (input.LA(1))
			{
			case 'n':
				{
				alt16 = 1;
				}
				break;
			case 'r':
				{
				alt16 = 2;
				}
				break;
			case 't':
				{
				alt16 = 3;
				}
				break;
			case '\'':
				{
				alt16 = 4;
				}
				break;
			case '\\':
				{
				alt16 = 5;
				}
				break;
			case 'u':
				{
				alt16 = 6;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 16, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// NCalc.g:296:5: 'n'
				{
				DebugLocation(296, 5);
				Match('n'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// NCalc.g:297:4: 'r'
				{
				DebugLocation(297, 4);
				Match('r'); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// NCalc.g:298:4: 't'
				{
				DebugLocation(298, 4);
				Match('t'); 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// NCalc.g:299:4: '\\''
				{
				DebugLocation(299, 4);
				Match('\''); 

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// NCalc.g:300:4: '\\\\'
				{
				DebugLocation(300, 4);
				Match('\\'); 

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// NCalc.g:301:4: UnicodeEscape
				{
				DebugLocation(301, 4);
				mUnicodeEscape(); 

				}
				break;

			}
			} finally { DebugExitSubRule(16); }


			}

		}
		finally
		{
			TraceOut("EscapeSequence", 43);
			LeaveRule("EscapeSequence", 43);
			LeaveRule_EscapeSequence();
		}
	}
	// $ANTLR end "EscapeSequence"

	partial void EnterRule_HexDigit();
	partial void LeaveRule_HexDigit();

	// $ANTLR start "HexDigit"
	[GrammarRule("HexDigit")]
	private void mHexDigit()
	{
		EnterRule_HexDigit();
		EnterRule("HexDigit", 44);
		TraceIn("HexDigit", 44);
		try
		{
			// NCalc.g:306:2: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(306, 2);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HexDigit", 44);
			LeaveRule("HexDigit", 44);
			LeaveRule_HexDigit();
		}
	}
	// $ANTLR end "HexDigit"

	partial void EnterRule_UnicodeEscape();
	partial void LeaveRule_UnicodeEscape();

	// $ANTLR start "UnicodeEscape"
	[GrammarRule("UnicodeEscape")]
	private void mUnicodeEscape()
	{
		EnterRule_UnicodeEscape();
		EnterRule("UnicodeEscape", 45);
		TraceIn("UnicodeEscape", 45);
		try
		{
			// NCalc.g:310:6: ( 'u' HexDigit HexDigit HexDigit HexDigit )
			DebugEnterAlt(1);
			// NCalc.g:310:12: 'u' HexDigit HexDigit HexDigit HexDigit
			{
			DebugLocation(310, 12);
			Match('u'); 
			DebugLocation(310, 16);
			mHexDigit(); 
			DebugLocation(310, 25);
			mHexDigit(); 
			DebugLocation(310, 34);
			mHexDigit(); 
			DebugLocation(310, 43);
			mHexDigit(); 

			}

		}
		finally
		{
			TraceOut("UnicodeEscape", 45);
			LeaveRule("UnicodeEscape", 45);
			LeaveRule_UnicodeEscape();
		}
	}
	// $ANTLR end "UnicodeEscape"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 46);
		TraceIn("WS", 46);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// NCalc.g:314:4: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
			DebugEnterAlt(1);
			// NCalc.g:314:7: ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' )
			{
			DebugLocation(314, 7);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||(input.LA(1)>='\f' && input.LA(1)<='\r')||input.LA(1)==' ')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(314, 37);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 46);
			LeaveRule("WS", 46);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_A();
	partial void LeaveRule_A();

	// $ANTLR start "A"
	[GrammarRule("A")]
	private void mA()
	{
		EnterRule_A();
		EnterRule("A", 47);
		TraceIn("A", 47);
		try
		{
			// NCalc.g:320:11: ( 'a' | 'A' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(320, 11);
			if (input.LA(1)=='A'||input.LA(1)=='a')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("A", 47);
			LeaveRule("A", 47);
			LeaveRule_A();
		}
	}
	// $ANTLR end "A"

	partial void EnterRule_B();
	partial void LeaveRule_B();

	// $ANTLR start "B"
	[GrammarRule("B")]
	private void mB()
	{
		EnterRule_B();
		EnterRule("B", 48);
		TraceIn("B", 48);
		try
		{
			// NCalc.g:321:11: ( 'b' | 'B' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(321, 11);
			if (input.LA(1)=='B'||input.LA(1)=='b')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("B", 48);
			LeaveRule("B", 48);
			LeaveRule_B();
		}
	}
	// $ANTLR end "B"

	partial void EnterRule_C();
	partial void LeaveRule_C();

	// $ANTLR start "C"
	[GrammarRule("C")]
	private void mC()
	{
		EnterRule_C();
		EnterRule("C", 49);
		TraceIn("C", 49);
		try
		{
			// NCalc.g:322:11: ( 'c' | 'C' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(322, 11);
			if (input.LA(1)=='C'||input.LA(1)=='c')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("C", 49);
			LeaveRule("C", 49);
			LeaveRule_C();
		}
	}
	// $ANTLR end "C"

	partial void EnterRule_D();
	partial void LeaveRule_D();

	// $ANTLR start "D"
	[GrammarRule("D")]
	private void mD()
	{
		EnterRule_D();
		EnterRule("D", 50);
		TraceIn("D", 50);
		try
		{
			// NCalc.g:323:11: ( 'd' | 'D' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(323, 11);
			if (input.LA(1)=='D'||input.LA(1)=='d')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("D", 50);
			LeaveRule("D", 50);
			LeaveRule_D();
		}
	}
	// $ANTLR end "D"

	partial void EnterRule_E();
	partial void LeaveRule_E();

	// $ANTLR start "E"
	[GrammarRule("E")]
	private void mE()
	{
		EnterRule_E();
		EnterRule("E", 51);
		TraceIn("E", 51);
		try
		{
			// NCalc.g:324:11: ( 'e' | 'E' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(324, 11);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("E", 51);
			LeaveRule("E", 51);
			LeaveRule_E();
		}
	}
	// $ANTLR end "E"

	partial void EnterRule_F();
	partial void LeaveRule_F();

	// $ANTLR start "F"
	[GrammarRule("F")]
	private void mF()
	{
		EnterRule_F();
		EnterRule("F", 52);
		TraceIn("F", 52);
		try
		{
			// NCalc.g:325:11: ( 'f' | 'F' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(325, 11);
			if (input.LA(1)=='F'||input.LA(1)=='f')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("F", 52);
			LeaveRule("F", 52);
			LeaveRule_F();
		}
	}
	// $ANTLR end "F"

	partial void EnterRule_G();
	partial void LeaveRule_G();

	// $ANTLR start "G"
	[GrammarRule("G")]
	private void mG()
	{
		EnterRule_G();
		EnterRule("G", 53);
		TraceIn("G", 53);
		try
		{
			// NCalc.g:326:11: ( 'g' | 'G' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(326, 11);
			if (input.LA(1)=='G'||input.LA(1)=='g')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("G", 53);
			LeaveRule("G", 53);
			LeaveRule_G();
		}
	}
	// $ANTLR end "G"

	partial void EnterRule_H();
	partial void LeaveRule_H();

	// $ANTLR start "H"
	[GrammarRule("H")]
	private void mH()
	{
		EnterRule_H();
		EnterRule("H", 54);
		TraceIn("H", 54);
		try
		{
			// NCalc.g:327:11: ( 'h' | 'H' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(327, 11);
			if (input.LA(1)=='H'||input.LA(1)=='h')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("H", 54);
			LeaveRule("H", 54);
			LeaveRule_H();
		}
	}
	// $ANTLR end "H"

	partial void EnterRule_I();
	partial void LeaveRule_I();

	// $ANTLR start "I"
	[GrammarRule("I")]
	private void mI()
	{
		EnterRule_I();
		EnterRule("I", 55);
		TraceIn("I", 55);
		try
		{
			// NCalc.g:328:11: ( 'i' | 'I' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(328, 11);
			if (input.LA(1)=='I'||input.LA(1)=='i')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("I", 55);
			LeaveRule("I", 55);
			LeaveRule_I();
		}
	}
	// $ANTLR end "I"

	partial void EnterRule_J();
	partial void LeaveRule_J();

	// $ANTLR start "J"
	[GrammarRule("J")]
	private void mJ()
	{
		EnterRule_J();
		EnterRule("J", 56);
		TraceIn("J", 56);
		try
		{
			// NCalc.g:329:11: ( 'j' | 'J' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(329, 11);
			if (input.LA(1)=='J'||input.LA(1)=='j')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("J", 56);
			LeaveRule("J", 56);
			LeaveRule_J();
		}
	}
	// $ANTLR end "J"

	partial void EnterRule_K();
	partial void LeaveRule_K();

	// $ANTLR start "K"
	[GrammarRule("K")]
	private void mK()
	{
		EnterRule_K();
		EnterRule("K", 57);
		TraceIn("K", 57);
		try
		{
			// NCalc.g:330:11: ( 'k' | 'K' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(330, 11);
			if (input.LA(1)=='K'||input.LA(1)=='k')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("K", 57);
			LeaveRule("K", 57);
			LeaveRule_K();
		}
	}
	// $ANTLR end "K"

	partial void EnterRule_L();
	partial void LeaveRule_L();

	// $ANTLR start "L"
	[GrammarRule("L")]
	private void mL()
	{
		EnterRule_L();
		EnterRule("L", 58);
		TraceIn("L", 58);
		try
		{
			// NCalc.g:331:11: ( 'l' | 'L' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(331, 11);
			if (input.LA(1)=='L'||input.LA(1)=='l')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("L", 58);
			LeaveRule("L", 58);
			LeaveRule_L();
		}
	}
	// $ANTLR end "L"

	partial void EnterRule_M();
	partial void LeaveRule_M();

	// $ANTLR start "M"
	[GrammarRule("M")]
	private void mM()
	{
		EnterRule_M();
		EnterRule("M", 59);
		TraceIn("M", 59);
		try
		{
			// NCalc.g:332:11: ( 'm' | 'M' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(332, 11);
			if (input.LA(1)=='M'||input.LA(1)=='m')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("M", 59);
			LeaveRule("M", 59);
			LeaveRule_M();
		}
	}
	// $ANTLR end "M"

	partial void EnterRule_N();
	partial void LeaveRule_N();

	// $ANTLR start "N"
	[GrammarRule("N")]
	private void mN()
	{
		EnterRule_N();
		EnterRule("N", 60);
		TraceIn("N", 60);
		try
		{
			// NCalc.g:333:11: ( 'n' | 'N' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(333, 11);
			if (input.LA(1)=='N'||input.LA(1)=='n')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("N", 60);
			LeaveRule("N", 60);
			LeaveRule_N();
		}
	}
	// $ANTLR end "N"

	partial void EnterRule_O();
	partial void LeaveRule_O();

	// $ANTLR start "O"
	[GrammarRule("O")]
	private void mO()
	{
		EnterRule_O();
		EnterRule("O", 61);
		TraceIn("O", 61);
		try
		{
			// NCalc.g:334:11: ( 'o' | 'O' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(334, 11);
			if (input.LA(1)=='O'||input.LA(1)=='o')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("O", 61);
			LeaveRule("O", 61);
			LeaveRule_O();
		}
	}
	// $ANTLR end "O"

	partial void EnterRule_P();
	partial void LeaveRule_P();

	// $ANTLR start "P"
	[GrammarRule("P")]
	private void mP()
	{
		EnterRule_P();
		EnterRule("P", 62);
		TraceIn("P", 62);
		try
		{
			// NCalc.g:335:11: ( 'p' | 'P' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(335, 11);
			if (input.LA(1)=='P'||input.LA(1)=='p')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("P", 62);
			LeaveRule("P", 62);
			LeaveRule_P();
		}
	}
	// $ANTLR end "P"

	partial void EnterRule_Q();
	partial void LeaveRule_Q();

	// $ANTLR start "Q"
	[GrammarRule("Q")]
	private void mQ()
	{
		EnterRule_Q();
		EnterRule("Q", 63);
		TraceIn("Q", 63);
		try
		{
			// NCalc.g:336:11: ( 'q' | 'Q' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(336, 11);
			if (input.LA(1)=='Q'||input.LA(1)=='q')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("Q", 63);
			LeaveRule("Q", 63);
			LeaveRule_Q();
		}
	}
	// $ANTLR end "Q"

	partial void EnterRule_R();
	partial void LeaveRule_R();

	// $ANTLR start "R"
	[GrammarRule("R")]
	private void mR()
	{
		EnterRule_R();
		EnterRule("R", 64);
		TraceIn("R", 64);
		try
		{
			// NCalc.g:337:11: ( 'r' | 'R' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(337, 11);
			if (input.LA(1)=='R'||input.LA(1)=='r')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("R", 64);
			LeaveRule("R", 64);
			LeaveRule_R();
		}
	}
	// $ANTLR end "R"

	partial void EnterRule_S();
	partial void LeaveRule_S();

	// $ANTLR start "S"
	[GrammarRule("S")]
	private void mS()
	{
		EnterRule_S();
		EnterRule("S", 65);
		TraceIn("S", 65);
		try
		{
			// NCalc.g:338:11: ( 's' | 'S' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(338, 11);
			if (input.LA(1)=='S'||input.LA(1)=='s')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("S", 65);
			LeaveRule("S", 65);
			LeaveRule_S();
		}
	}
	// $ANTLR end "S"

	partial void EnterRule_T();
	partial void LeaveRule_T();

	// $ANTLR start "T"
	[GrammarRule("T")]
	private void mT()
	{
		EnterRule_T();
		EnterRule("T", 66);
		TraceIn("T", 66);
		try
		{
			// NCalc.g:339:11: ( 't' | 'T' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(339, 11);
			if (input.LA(1)=='T'||input.LA(1)=='t')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("T", 66);
			LeaveRule("T", 66);
			LeaveRule_T();
		}
	}
	// $ANTLR end "T"

	partial void EnterRule_U();
	partial void LeaveRule_U();

	// $ANTLR start "U"
	[GrammarRule("U")]
	private void mU()
	{
		EnterRule_U();
		EnterRule("U", 67);
		TraceIn("U", 67);
		try
		{
			// NCalc.g:340:11: ( 'u' | 'U' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(340, 11);
			if (input.LA(1)=='U'||input.LA(1)=='u')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("U", 67);
			LeaveRule("U", 67);
			LeaveRule_U();
		}
	}
	// $ANTLR end "U"

	partial void EnterRule_V();
	partial void LeaveRule_V();

	// $ANTLR start "V"
	[GrammarRule("V")]
	private void mV()
	{
		EnterRule_V();
		EnterRule("V", 68);
		TraceIn("V", 68);
		try
		{
			// NCalc.g:341:11: ( 'v' | 'V' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(341, 11);
			if (input.LA(1)=='V'||input.LA(1)=='v')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("V", 68);
			LeaveRule("V", 68);
			LeaveRule_V();
		}
	}
	// $ANTLR end "V"

	partial void EnterRule_W();
	partial void LeaveRule_W();

	// $ANTLR start "W"
	[GrammarRule("W")]
	private void mW()
	{
		EnterRule_W();
		EnterRule("W", 69);
		TraceIn("W", 69);
		try
		{
			// NCalc.g:342:11: ( 'w' | 'W' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(342, 11);
			if (input.LA(1)=='W'||input.LA(1)=='w')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("W", 69);
			LeaveRule("W", 69);
			LeaveRule_W();
		}
	}
	// $ANTLR end "W"

	partial void EnterRule_X();
	partial void LeaveRule_X();

	// $ANTLR start "X"
	[GrammarRule("X")]
	private void mX()
	{
		EnterRule_X();
		EnterRule("X", 70);
		TraceIn("X", 70);
		try
		{
			// NCalc.g:343:11: ( 'x' | 'X' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(343, 11);
			if (input.LA(1)=='X'||input.LA(1)=='x')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("X", 70);
			LeaveRule("X", 70);
			LeaveRule_X();
		}
	}
	// $ANTLR end "X"

	partial void EnterRule_Y();
	partial void LeaveRule_Y();

	// $ANTLR start "Y"
	[GrammarRule("Y")]
	private void mY()
	{
		EnterRule_Y();
		EnterRule("Y", 71);
		TraceIn("Y", 71);
		try
		{
			// NCalc.g:344:11: ( 'y' | 'Y' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(344, 11);
			if (input.LA(1)=='Y'||input.LA(1)=='y')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("Y", 71);
			LeaveRule("Y", 71);
			LeaveRule_Y();
		}
	}
	// $ANTLR end "Y"

	partial void EnterRule_Z();
	partial void LeaveRule_Z();

	// $ANTLR start "Z"
	[GrammarRule("Z")]
	private void mZ()
	{
		EnterRule_Z();
		EnterRule("Z", 72);
		TraceIn("Z", 72);
		try
		{
			// NCalc.g:345:11: ( 'z' | 'Z' )
			DebugEnterAlt(1);
			// NCalc.g:
			{
			DebugLocation(345, 11);
			if (input.LA(1)=='Z'||input.LA(1)=='z')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("Z", 72);
			LeaveRule("Z", 72);
			LeaveRule_Z();
		}
	}
	// $ANTLR end "Z"

	public override void mTokens()
	{
		// NCalc.g:1:8: ( T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | T__63 | T__64 | T__65 | T__66 | T__67 | T__68 | T__69 | T__70 | T__71 | T__72 | T__73 | T__74 | T__75 | TRUE | FALSE | AND | OR | NOT | ID | INTEGER | FLOAT | STRING | DATETIME | NAME | EXPONENT | WS )
		int alt17=41;
		try { DebugEnterDecision(17, false);
		try
		{
			alt17 = dfa17.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(17); }
		switch (alt17)
		{
		case 1:
			DebugEnterAlt(1);
			// NCalc.g:1:10: T__48
			{
			DebugLocation(1, 10);
			mT__48(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// NCalc.g:1:16: T__49
			{
			DebugLocation(1, 16);
			mT__49(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// NCalc.g:1:22: T__50
			{
			DebugLocation(1, 22);
			mT__50(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// NCalc.g:1:28: T__51
			{
			DebugLocation(1, 28);
			mT__51(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// NCalc.g:1:34: T__52
			{
			DebugLocation(1, 34);
			mT__52(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// NCalc.g:1:40: T__53
			{
			DebugLocation(1, 40);
			mT__53(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// NCalc.g:1:46: T__54
			{
			DebugLocation(1, 46);
			mT__54(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// NCalc.g:1:52: T__55
			{
			DebugLocation(1, 52);
			mT__55(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// NCalc.g:1:58: T__56
			{
			DebugLocation(1, 58);
			mT__56(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// NCalc.g:1:64: T__57
			{
			DebugLocation(1, 64);
			mT__57(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// NCalc.g:1:70: T__58
			{
			DebugLocation(1, 70);
			mT__58(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// NCalc.g:1:76: T__59
			{
			DebugLocation(1, 76);
			mT__59(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// NCalc.g:1:82: T__60
			{
			DebugLocation(1, 82);
			mT__60(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// NCalc.g:1:88: T__61
			{
			DebugLocation(1, 88);
			mT__61(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// NCalc.g:1:94: T__62
			{
			DebugLocation(1, 94);
			mT__62(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// NCalc.g:1:100: T__63
			{
			DebugLocation(1, 100);
			mT__63(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// NCalc.g:1:106: T__64
			{
			DebugLocation(1, 106);
			mT__64(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// NCalc.g:1:112: T__65
			{
			DebugLocation(1, 112);
			mT__65(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// NCalc.g:1:118: T__66
			{
			DebugLocation(1, 118);
			mT__66(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// NCalc.g:1:124: T__67
			{
			DebugLocation(1, 124);
			mT__67(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// NCalc.g:1:130: T__68
			{
			DebugLocation(1, 130);
			mT__68(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// NCalc.g:1:136: T__69
			{
			DebugLocation(1, 136);
			mT__69(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// NCalc.g:1:142: T__70
			{
			DebugLocation(1, 142);
			mT__70(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// NCalc.g:1:148: T__71
			{
			DebugLocation(1, 148);
			mT__71(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// NCalc.g:1:154: T__72
			{
			DebugLocation(1, 154);
			mT__72(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// NCalc.g:1:160: T__73
			{
			DebugLocation(1, 160);
			mT__73(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// NCalc.g:1:166: T__74
			{
			DebugLocation(1, 166);
			mT__74(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// NCalc.g:1:172: T__75
			{
			DebugLocation(1, 172);
			mT__75(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// NCalc.g:1:178: TRUE
			{
			DebugLocation(1, 178);
			mTRUE(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// NCalc.g:1:183: FALSE
			{
			DebugLocation(1, 183);
			mFALSE(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// NCalc.g:1:189: AND
			{
			DebugLocation(1, 189);
			mAND(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// NCalc.g:1:193: OR
			{
			DebugLocation(1, 193);
			mOR(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// NCalc.g:1:196: NOT
			{
			DebugLocation(1, 196);
			mNOT(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// NCalc.g:1:200: ID
			{
			DebugLocation(1, 200);
			mID(); 

			}
			break;
		case 35:
			DebugEnterAlt(35);
			// NCalc.g:1:203: INTEGER
			{
			DebugLocation(1, 203);
			mINTEGER(); 

			}
			break;
		case 36:
			DebugEnterAlt(36);
			// NCalc.g:1:211: FLOAT
			{
			DebugLocation(1, 211);
			mFLOAT(); 

			}
			break;
		case 37:
			DebugEnterAlt(37);
			// NCalc.g:1:217: STRING
			{
			DebugLocation(1, 217);
			mSTRING(); 

			}
			break;
		case 38:
			DebugEnterAlt(38);
			// NCalc.g:1:224: DATETIME
			{
			DebugLocation(1, 224);
			mDATETIME(); 

			}
			break;
		case 39:
			DebugEnterAlt(39);
			// NCalc.g:1:233: NAME
			{
			DebugLocation(1, 233);
			mNAME(); 

			}
			break;
		case 40:
			DebugEnterAlt(40);
			// NCalc.g:1:238: EXPONENT
			{
			DebugLocation(1, 238);
			mEXPONENT(); 

			}
			break;
		case 41:
			DebugEnterAlt(41);
			// NCalc.g:1:247: WS
			{
			DebugLocation(1, 247);
			mWS(); 

			}
			break;

		}

	}


	#region DFA
	DFA10 dfa10;
	DFA17 dfa17;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa10 = new DFA10(this);
		dfa17 = new DFA17(this);
	}

	private class DFA10 : DFA
	{
		private const string DFA10_eotS =
			"\x3\xFFFF\x1\x6\x3\xFFFF";
		private const string DFA10_eofS =
			"\x7\xFFFF";
		private const string DFA10_minS =
			"\x2\x2E\x1\xFFFF\x1\x30\x3\xFFFF";
		private const string DFA10_maxS =
			"\x1\x39\x1\x65\x1\xFFFF\x1\x39\x3\xFFFF";
		private const string DFA10_acceptS =
			"\x2\xFFFF\x1\x1\x1\xFFFF\x1\x3\x1\x1\x1\x2";
		private const string DFA10_specialS =
			"\x7\xFFFF}>";
		private static readonly string[] DFA10_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x3\x1\xFFFF\xA\x1\xB\xFFFF\x1\x4\x1F\xFFFF\x1\x4",
				"",
				"\xA\x5",
				"",
				"",
				""
			};

		private static readonly short[] DFA10_eot = DFA.UnpackEncodedString(DFA10_eotS);
		private static readonly short[] DFA10_eof = DFA.UnpackEncodedString(DFA10_eofS);
		private static readonly char[] DFA10_min = DFA.UnpackEncodedStringToUnsignedChars(DFA10_minS);
		private static readonly char[] DFA10_max = DFA.UnpackEncodedStringToUnsignedChars(DFA10_maxS);
		private static readonly short[] DFA10_accept = DFA.UnpackEncodedString(DFA10_acceptS);
		private static readonly short[] DFA10_special = DFA.UnpackEncodedString(DFA10_specialS);
		private static readonly short[][] DFA10_transition;

		static DFA10()
		{
			int numStates = DFA10_transitionS.Length;
			DFA10_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA10_transition[i] = DFA.UnpackEncodedString(DFA10_transitionS[i]);
			}
		}

		public DFA10( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 10;
			this.eot = DFA10_eot;
			this.eof = DFA10_eof;
			this.min = DFA10_min;
			this.max = DFA10_max;
			this.accept = DFA10_accept;
			this.special = DFA10_special;
			this.transition = DFA10_transition;
		}

		public override string Description { get { return "262:1: FLOAT : ( ( DIGIT )* '.' ( DIGIT )+ ( EXPONENT )? | ( DIGIT )+ '.' ( DIGIT )* ( EXPONENT )? | ( DIGIT )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA17 : DFA
	{
		private const string DFA17_eotS =
			"\x1\xFFFF\x1\x21\x1\xFFFF\x1\x23\x2\xFFFF\x1\x25\x5\xFFFF\x1\x29\x1\x2B"+
			"\x1\x2E\x2\xFFFF\x1\x30\x1\xFFFF\x6\x1E\x1\x38\x17\xFFFF\x3\x1E\x1\x3C"+
			"\x2\x1E\x2\xFFFF\x2\x1E\x1\x40\x1\xFFFF\x1\x41\x1\x42\x1\x1E\x3\xFFFF"+
			"\x1\x44\x1\xFFFF";
		private const string DFA17_eofS =
			"\x45\xFFFF";
		private const string DFA17_minS =
			"\x1\x9\x1\x3D\x1\xFFFF\x1\x26\x2\xFFFF\x1\x2A\x5\xFFFF\x1\x3C\x2\x3D"+
			"\x2\xFFFF\x1\x7C\x1\xFFFF\x1\x52\x1\x41\x1\x4E\x1\x52\x1\x4F\x1\x2B\x1"+
			"\x2E\x17\xFFFF\x1\x55\x1\x4C\x1\x44\x1\x30\x1\x54\x1\x30\x2\xFFFF\x1"+
			"\x45\x1\x53\x1\x30\x1\xFFFF\x2\x30\x1\x45\x3\xFFFF\x1\x30\x1\xFFFF";
		private const string DFA17_maxS =
			"\x1\x7E\x1\x3D\x1\xFFFF\x1\x26\x2\xFFFF\x1\x2A\x5\xFFFF\x1\x3E\x1\x3D"+
			"\x1\x3E\x2\xFFFF\x1\x7C\x1\xFFFF\x1\x72\x1\x61\x1\x6E\x1\x72\x1\x6F\x1"+
			"\x39\x1\x65\x17\xFFFF\x1\x75\x1\x6C\x1\x64\x1\x7A\x1\x74\x1\x39\x2\xFFFF"+
			"\x1\x65\x1\x73\x1\x7A\x1\xFFFF\x2\x7A\x1\x65\x3\xFFFF\x1\x7A\x1\xFFFF";
		private const string DFA17_acceptS =
			"\x2\xFFFF\x1\x3\x1\xFFFF\x1\x6\x1\x7\x1\xFFFF\x1\xA\x1\xB\x1\xC\x1\xD"+
			"\x1\xE\x3\xFFFF\x1\x18\x1\x19\x1\xFFFF\x1\x1C\x7\xFFFF\x1\x24\x1\x25"+
			"\x1\x26\x1\x27\x1\x22\x1\x29\x1\x2\x1\x1\x1\x4\x1\x5\x1\x9\x1\x8\x1\x10"+
			"\x1\x11\x1\x12\x1\xF\x1\x14\x1\x13\x1\x16\x1\x17\x1\x15\x1\x1B\x1\x1A"+
			"\x6\xFFFF\x1\x28\x1\x23\x3\xFFFF\x1\x20\x3\xFFFF\x1\x1F\x1\x21\x1\x1D"+
			"\x1\xFFFF\x1\x1E";
		private const string DFA17_specialS =
			"\x45\xFFFF}>";
		private static readonly string[] DFA17_transitionS =
			{
				"\x2\x1F\x1\xFFFF\x2\x1F\x12\xFFFF\x1\x1F\x1\x1\x1\xFFFF\x1\x1C\x1\xFFFF"+
				"\x1\x2\x1\x3\x1\x1B\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x1\x9\x1\x1A\x1\xA"+
				"\xA\x19\x1\xB\x1\xFFFF\x1\xC\x1\xD\x1\xE\x1\xF\x1\xFFFF\x1\x15\x3\x1E"+
				"\x1\x18\x1\x14\x7\x1E\x1\x17\x1\x16\x4\x1E\x1\x13\x6\x1E\x1\x1D\x2\xFFFF"+
				"\x1\x10\x1\x1E\x1\xFFFF\x1\x15\x3\x1E\x1\x18\x1\x14\x7\x1E\x1\x17\x1"+
				"\x16\x4\x1E\x1\x13\x6\x1E\x1\xFFFF\x1\x11\x1\xFFFF\x1\x12",
				"\x1\x20",
				"",
				"\x1\x22",
				"",
				"",
				"\x1\x24",
				"",
				"",
				"",
				"",
				"",
				"\x1\x26\x1\x27\x1\x28",
				"\x1\x2A",
				"\x1\x2C\x1\x2D",
				"",
				"",
				"\x1\x2F",
				"",
				"\x1\x31\x1F\xFFFF\x1\x31",
				"\x1\x32\x1F\xFFFF\x1\x32",
				"\x1\x33\x1F\xFFFF\x1\x33",
				"\x1\x34\x1F\xFFFF\x1\x34",
				"\x1\x35\x1F\xFFFF\x1\x35",
				"\x1\x37\x1\xFFFF\x1\x37\x2\xFFFF\xA\x36",
				"\x1\x1A\x1\xFFFF\xA\x19\xB\xFFFF\x1\x1A\x1F\xFFFF\x1\x1A",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x39\x1F\xFFFF\x1\x39",
				"\x1\x3A\x1F\xFFFF\x1\x3A",
				"\x1\x3B\x1F\xFFFF\x1\x3B",
				"\xA\x1E\x7\xFFFF\x1A\x1E\x4\xFFFF\x1\x1E\x1\xFFFF\x1A\x1E",
				"\x1\x3D\x1F\xFFFF\x1\x3D",
				"\xA\x36",
				"",
				"",
				"\x1\x3E\x1F\xFFFF\x1\x3E",
				"\x1\x3F\x1F\xFFFF\x1\x3F",
				"\xA\x1E\x7\xFFFF\x1A\x1E\x4\xFFFF\x1\x1E\x1\xFFFF\x1A\x1E",
				"",
				"\xA\x1E\x7\xFFFF\x1A\x1E\x4\xFFFF\x1\x1E\x1\xFFFF\x1A\x1E",
				"\xA\x1E\x7\xFFFF\x1A\x1E\x4\xFFFF\x1\x1E\x1\xFFFF\x1A\x1E",
				"\x1\x43\x1F\xFFFF\x1\x43",
				"",
				"",
				"",
				"\xA\x1E\x7\xFFFF\x1A\x1E\x4\xFFFF\x1\x1E\x1\xFFFF\x1A\x1E",
				""
			};

		private static readonly short[] DFA17_eot = DFA.UnpackEncodedString(DFA17_eotS);
		private static readonly short[] DFA17_eof = DFA.UnpackEncodedString(DFA17_eofS);
		private static readonly char[] DFA17_min = DFA.UnpackEncodedStringToUnsignedChars(DFA17_minS);
		private static readonly char[] DFA17_max = DFA.UnpackEncodedStringToUnsignedChars(DFA17_maxS);
		private static readonly short[] DFA17_accept = DFA.UnpackEncodedString(DFA17_acceptS);
		private static readonly short[] DFA17_special = DFA.UnpackEncodedString(DFA17_specialS);
		private static readonly short[][] DFA17_transition;

		static DFA17()
		{
			int numStates = DFA17_transitionS.Length;
			DFA17_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA17_transition[i] = DFA.UnpackEncodedString(DFA17_transitionS[i]);
			}
		}

		public DFA17( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 17;
			this.eot = DFA17_eot;
			this.eof = DFA17_eof;
			this.min = DFA17_min;
			this.max = DFA17_max;
			this.accept = DFA17_accept;
			this.special = DFA17_special;
			this.transition = DFA17_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | T__63 | T__64 | T__65 | T__66 | T__67 | T__68 | T__69 | T__70 | T__71 | T__72 | T__73 | T__74 | T__75 | TRUE | FALSE | AND | OR | NOT | ID | INTEGER | FLOAT | STRING | DATETIME | NAME | EXPONENT | WS );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion

}

} // namespace  NCalc 
