<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>Default Parlot-based parser for NCalc expressions, including parser options and argument separator configuration.</Description>
        <SignAssembly>true</SignAssembly>
        <RootNamespace>NCalc</RootNamespace>
        <AssemblyOriginatorKeyFile>../../NCalc.snk</AssemblyOriginatorKeyFile>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);NCalc</InterceptorsNamespaces>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>obj\$(Configuration)\$(TargetFramework)</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NCalc.Domain\NCalc.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Parlot" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../NCalc.png">
            <Pack>True</Pack>
            <PackagePath>/</PackagePath>
        </None>
    </ItemGroup>

</Project>
