using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using NCalc.SourceGenerators.Helpers;
using NCalc.SourceGenerators.Models;

namespace NCalc.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class BinaryOperatorsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static sourceContext =>
            sourceContext.AddSource("BinaryOperators.g.cs", SourceText.From(GenerateSource(), Encoding.UTF8)));
    }

    private static string GenerateSource()
    {
        var metadata = NumericTypeMetadataProvider.GetMetadata();
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace NCalc.Helpers;");
        builder.AppendLine();
        builder.AppendLine("internal static class BinaryOperators");
        builder.AppendLine("{");

        GeneratePublicDispatch(builder, "Add", checkedVariant: true);
        GeneratePublicDispatch(builder, "Subtract", checkedVariant: true);
        GeneratePublicDispatch(builder, "Multiply", checkedVariant: true);
        GeneratePublicDispatch(builder, "Divide", checkedVariant: true);
        GeneratePublicDispatch(builder, "Modulo", checkedVariant: false);

        GenerateOperation(builder, metadata, "AddUnchecked", "+", checkedExpression: false);
        GenerateOperation(builder, metadata, "SubtractUnchecked", "-", checkedExpression: false);
        GenerateOperation(builder, metadata, "MultiplyUnchecked", "*", checkedExpression: false);
        GenerateOperation(builder, metadata, "DivideUnchecked", "/", checkedExpression: false);
        GenerateOperation(builder, metadata, "ModuloUnchecked", "%", checkedExpression: false);
        GenerateOperation(builder, metadata, "AddChecked", "+", checkedExpression: true);
        GenerateOperation(builder, metadata, "SubtractChecked", "-", checkedExpression: true);
        GenerateOperation(builder, metadata, "MultiplyChecked", "*", checkedExpression: true);
        GenerateOperation(builder, metadata, "DivideChecked", "/", checkedExpression: true);

        builder.AppendLine("    private static string FormatError(object? a, string op, object? b)");
        builder.AppendLine("    {");
        builder.AppendLine("        var aType = a?.GetType()?.Name;");
        builder.AppendLine("        var bType = b?.GetType()?.Name;");
        builder.AppendLine();
        builder.AppendLine("        return $\"{a} {op} {b}: {aType}, {bType}\";");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static T CheckOverflow<T>(T value)");
        builder.AppendLine("    {");
        builder.AppendLine("        switch (value)");
        builder.AppendLine("        {");
        builder.AppendLine("            case double doubleValue when double.IsInfinity(doubleValue):");
        builder.AppendLine("            case float floatValue when float.IsInfinity(floatValue):");
        builder.AppendLine("                throw new System.OverflowException(\"Arithmetic operation resulted in an overflow\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return value;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GeneratePublicDispatch(StringBuilder builder, string methodName, bool checkedVariant)
    {
        if (checkedVariant)
        {
            builder.AppendLine($"    public static object {methodName}(object a, object b, bool overflowProtection)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (overflowProtection)");
            builder.AppendLine("        {");
            builder.AppendLine($"            return {methodName}Checked(a, b);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine($"        return {methodName}Unchecked(a, b);");
            builder.AppendLine("    }");
        }
        else
        {
            builder.AppendLine($"    public static object {methodName}(object a, object b)");
            builder.AppendLine("    {");
            builder.AppendLine($"        return {methodName}Unchecked(a, b);");
            builder.AppendLine("    }");
        }

        builder.AppendLine();
    }

    private static void GenerateOperation(
        StringBuilder builder,
        NumericTypeMetadata metadata,
        string methodName,
        string operatorSymbol,
        bool checkedExpression)
    {
        builder.AppendLine($"    private static object {methodName}(object a, object b)");
        builder.AppendLine("    {");
        builder.AppendLine("        switch (a)");
        builder.AppendLine("        {");

        foreach (var numericType in metadata.BinaryOperatorTypes)
        {
            builder.AppendLine($"            case {numericType.Keyword} aa when b is {numericType.Keyword} bb:");
            builder.Append("                return ");

            if (checkedExpression)
            {
                builder.Append("CheckOverflow(checked(");
            }

            builder.Append($"aa {operatorSymbol} bb");

            if (checkedExpression)
            {
                builder.Append("))");
            }

            builder.AppendLine(";");
        }

        builder.AppendLine("            default:");
        builder.AppendLine($"                throw new System.InvalidOperationException(FormatError(a, \"{operatorSymbol}\", b));");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
