using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using NCalc.SourceGenerators.Helpers;
using NCalc.SourceGenerators.Models;

namespace NCalc.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class TypeHelperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static sourceContext =>
            sourceContext.AddSource("TypeHelper.Numeric.g.cs", SourceText.From(GenerateSource(), Encoding.UTF8)));
    }

    private static string GenerateSource()
    {
        var metadata = NumericTypeMetadataProvider.GetMetadata();
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine("namespace NCalc.Helpers;");
        builder.AppendLine();
        builder.AppendLine("public static partial class TypeHelper");
        builder.AppendLine("{");

        GenerateMostPreciseType(builder, metadata);
        GenerateMostPreciseNumberType(builder, metadata);
        GenerateCanConvertPrimitiveImplicitly(builder, metadata);
        GenerateIsNumberType(builder, metadata);
        GenerateIsReal(builder, metadata);
        GenerateIsUnsignedType(builder, metadata);
        GenerateTypeCodeExpandBits(builder, metadata);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GenerateMostPreciseType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    private static Type GetMostPreciseType(Type? a, Type? b)");
        builder.AppendLine("    {");

        foreach (var type in metadata.BuiltInTypeOrder)
        {
            builder.AppendLine($"        if (a == typeof({type}) || b == typeof({type}))");
            builder.AppendLine("        {");
            builder.AppendLine($"            return typeof({type});");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return a ?? typeof(object);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateMostPreciseNumberType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static Type? GetMostPreciseNumberType(Type a, Type b)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!IsNumberType(a) || !IsNumberType(b))");
        builder.AppendLine("        {");
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();

        foreach (var type in metadata.NumberPrecedence)
        {
            builder.AppendLine($"        if (a == typeof({type}) || b == typeof({type}))");
            builder.AppendLine("        {");
            builder.AppendLine($"            return typeof({type});");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return null;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateCanConvertPrimitiveImplicitly(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static bool CanConvertPrimitiveImplicitly(Type from, Type to)");
        builder.AppendLine("    {");

        foreach (var type in metadata.PrimitiveConversionTypes)
        {
            builder.AppendLine($"        if (from == typeof({type.Keyword}))");
            builder.AppendLine("        {");
            builder.AppendLine($"            return {GenerateTypeComparisonExpression("to", type.ImplicitConversions ?? [])};");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateIsNumberType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    private static bool IsNumberType(Type type)");
        builder.AppendLine("    {");

        foreach (var type in metadata.NumberPrecedence)
        {
            builder.AppendLine($"        if (type == typeof({type}))");
            builder.AppendLine("        {");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateIsReal(StringBuilder builder, NumericTypeMetadata metadata)
    {
        var realTypes = metadata.BinaryOperatorTypes.Where(type => type.IsReal);

        builder.AppendLine("    public static bool IsReal(object? value)");
        builder.AppendLine("    {");

        foreach (var type in realTypes)
        {
            builder.AppendLine($"        if (value is {type.Keyword})");
            builder.AppendLine("        {");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateIsUnsignedType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        var unsignedTypes = metadata.BinaryOperatorTypes.Where(type => type.IsUnsigned);

        builder.AppendLine("    public static bool IsUnsignedType(object? value)");
        builder.AppendLine("    {");

        foreach (var type in unsignedTypes)
        {
            builder.AppendLine($"        if (value is {type.Keyword})");
            builder.AppendLine("        {");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateTypeCodeExpandBits(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static TypeCode TypeCodeExpandBits(TypeCode typeCode)");
        builder.AppendLine("    {");

        foreach (var group in metadata.TypeCodeExpandBitsTypes.GroupBy(type => type.ExpandBitsTypeCode))
        {
            builder.AppendLine($"        if ({GenerateTypeCodeComparisonExpression("typeCode", group)})");
            builder.AppendLine("        {");
            builder.AppendLine($"            return {group.Key};");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return TypeCode.Empty;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string GenerateTypeComparisonExpression(string parameterName, string[] types)
    {
        return types.Length == 0
            ? "false"
            : string.Join(" || ", types.Select(type => $"{parameterName} == typeof({type})"));
    }

    private static string GenerateTypeCodeComparisonExpression(
        string parameterName,
        IEnumerable<NumericTypeDefinition> types)
    {
        return string.Join(" || ", types.Select(type => $"{parameterName} == {type.TypeCode}"));
    }
}
