using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using NCalc.SourceGenerators.Helpers;
using NCalc.SourceGenerators.Models;

namespace NCalc.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class TypeHelperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static sourceContext =>
            sourceContext.AddSource("TypeHelper.Numeric.g.cs", SourceText.From(GenerateSource(), Encoding.UTF8)));
    }

    private static string GenerateSource()
    {
        var metadata = NumericTypeMetadataProvider.GetMetadata();
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine("namespace NCalc.Helpers;");
        builder.AppendLine();
        builder.AppendLine("public static partial class TypeHelper");
        builder.AppendLine("{");

        GenerateCompareUsingMostPreciseType(builder, metadata);
        GenerateMostPreciseNumberType(builder, metadata);
        GenerateCanConvertPrimitiveImplicitly(builder, metadata);
        GenerateIsNumberType(builder, metadata);
        GenerateIsReal(builder, metadata);
        GenerateIsUnsignedType(builder, metadata);
        GenerateTypeCodeExpandBits(builder, metadata);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GenerateCompareUsingMostPreciseType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static ComparisonResult CompareUsingMostPreciseType(object? a, object? b, StringComparer stringComparer, CultureInfo cultureInfo)");
        builder.AppendLine("    {");

        foreach (var type in metadata.BuiltInTypeOrder)
        {
            if (type == "object")
            {
                continue;
            }

            var typeDefinition = metadata.Types.SingleOrDefault(definition => definition.Keyword == type);

            if (typeDefinition is { SupportsSameTypeComparison: true })
            {
                GenerateSameTypeComparison(builder, typeDefinition);
            }

            builder.AppendLine($"        if ({GenerateTypeMatchExpression(type)})");
            builder.AppendLine("        {");

            if (typeDefinition?.SupportsNaN == true)
            {
                GenerateFloatingPointComparison(builder, type);
            }
            else if (type == "string")
            {
                GenerateStringComparison(builder);
            }
            else
            {
                GenerateValueTypeComparison(builder, type);
            }

            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        var comparisonType = a?.GetType() ?? b?.GetType() ?? typeof(object);");
        builder.AppendLine("        var convertedA = a != null ? Convert.ChangeType(a, comparisonType, cultureInfo) : null;");
        builder.AppendLine("        var convertedB = b != null ? Convert.ChangeType(b, comparisonType, cultureInfo) : null;");
        builder.AppendLine();
        GenerateComparisonResult(builder, "System.Collections.Comparer.Default.Compare(convertedA, convertedB)");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string GenerateTypeMatchExpression(string type)
    {
        return $"a is {type} || b is {type}";
    }

    private static void GenerateSameTypeComparison(StringBuilder builder, NumericTypeDefinition typeDefinition)
    {
        var type = typeDefinition.Keyword;
        var left = $"{type}Left";
        var right = $"{type}Right";

        builder.AppendLine($"        if (a is {type} {left} && b is {type} {right})");
        builder.AppendLine("        {");

        if (typeDefinition.SupportsNaN)
        {
            builder.AppendLine($"            if ({type}.IsNaN({left}) || {type}.IsNaN({right}))");
            builder.AppendLine("                return ComparisonResult.Unordered;");
            builder.AppendLine();
        }

        GenerateComparisonResult(builder, $"{left}.CompareTo({right})");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void GenerateFloatingPointComparison(StringBuilder builder, string type)
    {
        var conversionMethod = type == "double" ? "ToDouble" : "ToSingle";

        builder.AppendLine($"            var left = Convert.{conversionMethod}(a, cultureInfo);");
        builder.AppendLine($"            var right = Convert.{conversionMethod}(b, cultureInfo);");
        builder.AppendLine();
        builder.AppendLine($"            if ({type}.IsNaN(left) || {type}.IsNaN(right))");
        builder.AppendLine("                return ComparisonResult.Unordered;");
        builder.AppendLine();
        GenerateComparisonResult(builder, "left.CompareTo(right)");
    }

    private static void GenerateStringComparison(StringBuilder builder)
    {
        builder.AppendLine("            var left = a != null ? Convert.ToString(a, cultureInfo) : null;");
        builder.AppendLine("            var right = b != null ? Convert.ToString(b, cultureInfo) : null;");
        builder.AppendLine();
        GenerateComparisonResult(builder, "stringComparer.Compare(left, right)");
    }

    private static void GenerateValueTypeComparison(StringBuilder builder, string type)
    {
        var conversionMethod = type switch
        {
            "decimal" => "ToDecimal",
            "long" => "ToInt64",
            "ulong" => "ToUInt64",
            "int" => "ToInt32",
            "uint" => "ToUInt32",
            "short" => "ToInt16",
            "ushort" => "ToUInt16",
            "byte" => "ToByte",
            "sbyte" => "ToSByte",
            "char" => "ToChar",
            "bool" => "ToBoolean",
            _ => throw new InvalidOperationException($"Unsupported value type '{type}'.")
        };

        builder.AppendLine($"            {type}? left = a != null ? Convert.{conversionMethod}(a, cultureInfo) : null;");
        builder.AppendLine($"            {type}? right = b != null ? Convert.{conversionMethod}(b, cultureInfo) : null;");
        builder.AppendLine();
        GenerateComparisonResult(builder, "Nullable.Compare(left, right)");
    }

    private static void GenerateComparisonResult(StringBuilder builder, string comparisonExpression)
    {
        builder.AppendLine($"            return {comparisonExpression} switch");
        builder.AppendLine("            {");
        builder.AppendLine("                < 0 => ComparisonResult.Less,");
        builder.AppendLine("                > 0 => ComparisonResult.Greater,");
        builder.AppendLine("                _ => ComparisonResult.Equal");
        builder.AppendLine("            };");
    }

    private static void GenerateMostPreciseNumberType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static Type? GetMostPreciseNumberType(Type a, Type b)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!IsNumberType(a) || !IsNumberType(b))");
        builder.AppendLine("        {");
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();

        foreach (var type in metadata.NumberPrecedence)
        {
            builder.AppendLine($"        if (a == typeof({type}) || b == typeof({type}))");
            builder.AppendLine("        {");
            builder.AppendLine($"            return typeof({type});");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return null;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateCanConvertPrimitiveImplicitly(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static bool CanConvertPrimitiveImplicitly(Type from, Type to)");
        builder.AppendLine("    {");

        foreach (var type in metadata.PrimitiveConversionTypes)
        {
            builder.AppendLine($"        if (from == typeof({type.Keyword}))");
            builder.AppendLine("        {");
            builder.AppendLine($"            return {GenerateTypeComparisonExpression("to", type.ImplicitConversions ?? [])};");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateIsNumberType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    private static bool IsNumberType(Type type)");
        builder.AppendLine("    {");

        foreach (var type in metadata.NumberPrecedence)
        {
            builder.AppendLine($"        if (type == typeof({type}))");
            builder.AppendLine("        {");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateIsReal(StringBuilder builder, NumericTypeMetadata metadata)
    {
        var realTypes = metadata.BinaryOperatorTypes.Where(type => type.IsReal);

        builder.AppendLine("    public static bool IsReal(object? value)");
        builder.AppendLine("    {");
        builder.AppendLine("        switch (value)");
        builder.AppendLine("        {");

        foreach (var type in realTypes)
        {
            builder.AppendLine($"            case {type.Keyword}:");
        }

        builder.AppendLine("                return true;");
        builder.AppendLine("            default:");
        builder.AppendLine("                return false;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateIsUnsignedType(StringBuilder builder, NumericTypeMetadata metadata)
    {
        var unsignedTypes = metadata.BinaryOperatorTypes.Where(type => type.IsUnsigned);

        builder.AppendLine("    public static bool IsUnsignedType(object? value)");
        builder.AppendLine("    {");
        builder.AppendLine("        switch (value)");
        builder.AppendLine("        {");

        foreach (var type in unsignedTypes)
        {
            builder.AppendLine($"            case {type.Keyword}:");
        }

        builder.AppendLine("                return true;");
        builder.AppendLine("            default:");
        builder.AppendLine("                return false;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateTypeCodeExpandBits(StringBuilder builder, NumericTypeMetadata metadata)
    {
        builder.AppendLine("    public static TypeCode TypeCodeExpandBits(TypeCode typeCode)");
        builder.AppendLine("    {");
        builder.AppendLine("        switch (typeCode)");
        builder.AppendLine("        {");

        foreach (var group in metadata.TypeCodeExpandBitsTypes.GroupBy(type => type.ExpandBitsTypeCode))
        {
            foreach (var type in group)
            {
                builder.AppendLine($"            case {type.TypeCode}:");
            }

            builder.AppendLine($"                return {group.Key};");
        }

        builder.AppendLine("            default:");
        builder.AppendLine("                return TypeCode.Empty;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string GenerateTypeComparisonExpression(string parameterName, string[] types)
    {
        return types.Length == 0
            ? "false"
            : string.Join(" || ", types.Select(type => $"{parameterName} == typeof({type})"));
    }
}
